/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

/**
 *
 * @author longnguyen
 */
public class ScreenTitles {

    //Create Journey Screen
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_JOURNEY_NEXT = "Next";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_JOURNEY_NEXT_ID = "SCREEN_COMPONENT_BUTTON_CREATE_JOURNEY_NEXT_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME = "Name";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME_MESSAGE = "Please provide name for this Journey";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER = "No. of Field Researcher";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_MESSAGE = "Please provide No. of Field Researcher for this Journey";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_VALIDATOR_MESSAGE = "Please provide a number which is greater than 1 for No. of Field Researcher";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_CONVERTER_MESSAGE = "Please enter number only for No. of Field Researcher";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE = "Start Date";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE_ID = "SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE_ID";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE_MESSAGE = "Please provide start date for this Journey";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE = "End Date";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE_ID = "SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE_ID";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE_MESSAGE = "Please provide end date for this Journey";
    public static final String SCREEN_COMPONENT_TEXT_AREA_CREATE_JOURNEY_DESCRIPTION = "Description";
    public static final String SCREEN_COMPONENT_TEXT_AREA_CREATE_JOURNEY_DESCRIPTION_ID = "SCREEN_COMPONENT_TEXT_AREA_CREATE_JOURNEY_DESCRIPTION_ID";    
    public static final String SCREEN_COMPONENT_GROWL_CREATE_JOURNEY_FOR = "SCREEN_COMPONENT_GROWL_CREATE_JOURNEY_FOR";

    //Add Touch Point Screen
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD = "Add Touch Point";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_ID";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_AJAX_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_AJAX_ID";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE = "Save";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE_ID"; 
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE_MESSAGE = "Please add Touch Point to this Journey"; 
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_HIDDEN_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_HIDDEN_ID";
    public static final String SCREEN_COMPONENT_DIAGRAM_ADD_TOUCH_POINT_TOUCH_POINT_VISUALIZATION_ID = "SCREEN_COMPONENT_DIAGRAM_ADD_TOUCH_POINT_TOUCH_POINT_VISUALIZATION_ID";
    public static final String SCREEN_COMPONENT_FORM_ID = "SCREEN_COMPONENT_FORM_ID";
    public static final String SCREEN_COMPONENT_JS_FUNCTION_OPEN_TOUCH_POINT_LOCATION_DIALOG = "openTouchPointLocationDialog()";

    //Create Touch Point Dialog
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_ADD = "Add";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_ADD_ID = "SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_ADD_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME = "Name";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME_MESSAGE = "Please provide name for this Touch Point";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION = "Action";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION_MESSAGE = "Please provide action for this Touch Point";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_DURATION = "DURATION";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_DURATION_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_DURATION_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_DURATION_MESSAGE = "Please provide duration of Touch Point";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_SPECFIY_LOCATION = "Specify Location";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_SPECFIY_LOCATION_ID = "SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_SPECFIY_LOCATION_ID";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_CHANNEL = "Select Channel";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_CHANNEL_ID = "SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_CHANNEL_ID";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_CHANNEL_MESSAGE = "Please provide channel for this Touch Point";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_CHANNEL_DESCRIPTION = "Please enter URL";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_CHANNEL_DESCRIPTION_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_CHANNEL_DESCRIPTION_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_CHANNEL_DESCRIPTION_MESSAGE = "Please provide URL of Website";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_DURATION_UNIT_ID = "Duration_Unit";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_DURATION_UNIT_MESSAGE = "Please provide Duration Unit";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_DURATION_UNIT = "Days/Hours/Mins";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_DURATION_ID = "Duration";
    public static final String SCREEN_COMPONENT_DROP_DOWN_CREATE_TOUCH_POINT_DURATION_MESSAGE = "Specify expected Duration";
    

    //Touch Point Location Dialog
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_ADDRESS = "Address";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_ADDRESS_ID = "address";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_ADDRESS_MESSAGE = "Please provide address for this Touch Point";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS = "Radius";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS_ID = "SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS_MESSAGE = "Please provide radius for this Touch Point.";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET = "Set Location of this Touch Point";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET_ID = "SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET_ID";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET_MESSAGE = "Location of this Touch Point has not been set yet. Please make sure that you can see the marker on map.";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_LOCATE = "Locate";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_LOCATE_ID = "SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_LOCATE_ID";
    public static final String SCREEN_COMPONENT_GMAP_TOUCH_POINT_LOCATION_ID = "SCREEN_COMPONENT_GMAP_TOUCH_POINT_LOCATION_ID";
    public static final String SCREEN_COMPONENT_JS_FUNCTION_LOCATE_TOUCH_POINT = "locateTouchPoint()";
    
    //Login Screen
    public static final String SCREEN_COMPONENT_BUTTON_LOGIN_RESET_PASSWORD = "Reset Password";
    public static final String SCREEN_COMPONENT_BUTTON_LOGIN_RESET_PASSWORD_ID = "SCREEN_COMPONENT_BUTTON_LOGIN_RESET_PASSWORD_ID";
    public static final String SCREEN_COMPONENT_BUTTON_LOGIN_LOGIN = "Login";
    public static final String SCREEN_COMPONENT_BUTTON_LOGIN_LOGIN_ID = "SCREEN_COMPONENT_BUTTON_LOGIN_LOGIN_ID";
    
    //Global
    public static final String SCREEN_COMPONENT_MESSAGES_ID = "SCREEN_COMPONENT_MESSAGES_ID";
}
