/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

/**
 *
 * @author longnguyen
 */
public class ScreenTitles {

    //Create Journey Screen
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_JOURNEY_NEXT = "Next";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_JOURNEY_NEXT_ID = "SCREEN_COMPONENT_BUTTON_CREATE_JOURNEY_NEXT_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME = "Name";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NAME_MESSAGE = "Please provide name for this Journey";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER = "No. of Field Researcher";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_JOURNEY_NO_OF_FIELD_RESEARCHER_MESSAGE = "Please provide No. of Field Researcher for this Journey";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE = "Start Date";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE_ID = "SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE_ID";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_START_DATE_MESSAGE = "Please provide start date for this Journey";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE = "End Date";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE_ID = "SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE_ID";
    public static final String SCREEN_COMPONENT_CALENDAR_CREATE_JOURNEY_END_DATE_MESSAGE = "Please provide end date for this Journey";
    public static final String SCREEN_COMPONENT_TEXT_AREA_CREATE_JOURNEY_DESCRIPTION = "Description";
    public static final String SCREEN_COMPONENT_TEXT_AREA_CREATE_JOURNEY_DESCRIPTION_ID = "SCREEN_COMPONENT_TEXT_AREA_CREATE_JOURNEY_DESCRIPTION_ID";    

    //Add Touch Point Screen
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD = "Add Touch Point";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_ID";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_AJAX_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_ADD_AJAX_ID";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE = "Save";
    public static final String SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE_ID = "SCREEN_COMPONENT_BUTTON_ADD_TOUCH_POINT_SAVE_ID";

    //Create Touch Point Dialog
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_ADD = "Add";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_ADD_ID = "SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_ADD_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME = "Name";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_NAME_MESSAGE = "Please provide name for this Touch Point";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION = "Action";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION_ID = "SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION_ID";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_CREATE_TOUCH_POINT_ACTION_MESSAGE = "Please provide action for this Touch Point";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_SPECFIY_LOCATION = "Specify Location";
    public static final String SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_SPECFIY_LOCATION_ID = "SCREEN_COMPONENT_BUTTON_CREATE_TOUCH_POINT_SPECFIY_LOCATION_ID";

    //Touch Point Location Dialog
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_ADDRESS = "Address";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_ADDRESS_ID = "address";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_ADDRESS_MESSAGE = "Please provide location of this Touch Point";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS = "Radius";
    public static final String SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS_ID = "SCREEN_COMPONENT_TEXT_FIELD_TOUCH_POINT_LOCATION_RADIUS_ID";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET = "Set";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET_ID = "SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_SET_ID";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_LOCATE = "Locate";
    public static final String SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_LOCATE_ID = "SCREEN_COMPONENT_BUTTON_TOUCH_POINT_LOCATION_LOCATE_ID";
}
